name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '44 13 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue was automatically marked inactive.'
        stale-pr-message: 'This Pull Request was automatically marked inactive.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'